### PR TITLE
feat(example_api_events.py): Add example for new events endpoint

### PR DESCRIPTION
**Pull request by nuclearcat**
Provide example how to use new events endpoint.

### CODE REVIEW

**Comment by JenySadadia** [comment]
We should also have a section for this in the docs.

**Comment by nuclearcat** [comment]
Where would be the best place to put this?

**Comment by JenySadadia** [comment]
How about https://docs.kernelci.org/maestro/api/api-details/#pubsub-and-cloudevent ?

**Comment by nuclearcat** [comment]
Merging and will prepare documentation PR for kernelci-api

**Pull request merged**
