### PR TITLE
Rework pipeline with Scheduler class

### PR DESCRIPTION
**Pull request by gctucker**
Rework the pipeline YAML configuration with the new `run_on` attribute and the scheduler configuration and logic from the `Scheduler` class.

### CODE REVIEW

**Comment by JenySadadia** [comment]
This is breaking `runner` on staging:
```
today at 17:03:38Traceback (most recent call last):
today at 17:03:38  File "/home/kernelci/./pipeline/runner.py", line 126, in <module>
today at 17:03:38    status = opts.command(configs, opts)
today at 17:03:38  File "/home/kernelci/./pipeline/runner.py", line 120, in __call__
today at 17:03:38    return Runner(configs, args).run()
today at 17:03:38  File "/home/kernelci/./pipeline/runner.py", line 39, in __init__
today at 17:03:38    runtimes = dict(kernelci.runtime.get_all_runtimes(rconfigs, args))
today at 17:03:38AttributeError: module 'kernelci.runtime' has no attribute 'get_all_runtimes'. Did you mean: 'get_runtime'?
today at 17:03:43Container stopped
```

**Comment by gctucker** [comment]
Ah I think the issue is rather that some kernelci-core changes had some conflicts and didn't make it into the Docker image.  Taking a look.

**Comment by gctucker** [comment]
Fixed in `kernelci-core` at tag `staging-20230530.0`, building the Docker image now

**Comment by JenySadadia** [comment]
Also, I was getting this locally.
```
kernelci-pipeline-runner-docker | Pulling image kernelci/staging-gcc-10:x86-kunit-kernelci
kernelci-pipeline-runner-docker | Starting container
kernelci-pipeline-runner-docker | 05/29/2023 07:20:42 AM UTC [ERROR] Traceback (most recent call last):
kernelci-pipeline-runner-docker |   File "/usr/local/lib/python3.10/site-packages/docker/api/client.py", line 261, in _raise_for_status
kernelci-pipeline-runner-docker |     response.raise_for_status()
kernelci-pipeline-runner-docker |   File "/usr/local/lib/python3.10/site-packages/requests/models.py", line 1021, in raise_for_status
kernelci-pipeline-runner-docker |     raise HTTPError(http_error_msg, response=self)
kernelci-pipeline-runner-docker | requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: http+docker://localhost/v1.35/containers/create
kernelci-pipeline-runner-docker | 
kernelci-pipeline-runner-docker | During handling of the above exception, another exception occurred:
kernelci-pipeline-runner-docker | 
kernelci-pipeline-runner-docker | Traceback (most recent call last):
kernelci-pipeline-runner-docker |   File "/home/kernelci/pipeline/base.py", line 69, in run
kernelci-pipeline-runner-docker |     status = self._run(context)
kernelci-pipeline-runner-docker |   File "/home/kernelci/./pipeline/runner.py", line 94, in _run
kernelci-pipeline-runner-docker |     job_obj = self._runtime.submit(output_file)
kernelci-pipeline-runner-docker |   File "/usr/local/lib/python3.10/site-packages/kernelci-1.1-py3.10.egg/kernelci/runtime/docker.py", line 69, in submit
kernelci-pipeline-runner-docker |     return self._client.containers.run(
kernelci-pipeline-runner-docker |   File "/usr/local/lib/python3.10/site-packages/docker/models/containers.py", line 802, in run
kernelci-pipeline-runner-docker |     container = self.create(image=image, command=command,
kernelci-pipeline-runner-docker |   File "/usr/local/lib/python3.10/site-packages/docker/models/containers.py", line 861, in create
kernelci-pipeline-runner-docker |     resp = self.client.api.create_container(**create_kwargs)
kernelci-pipeline-runner-docker |   File "/usr/local/lib/python3.10/site-packages/docker/api/container.py", line 430, in create_container
kernelci-pipeline-runner-docker |     return self.create_container_from_config(config, name)
kernelci-pipeline-runner-docker |   File "/usr/local/lib/python3.10/site-packages/docker/api/container.py", line 441, in create_container_from_config
kernelci-pipeline-runner-docker |     return self._result(res, True)
kernelci-pipeline-runner-docker |   File "/usr/local/lib/python3.10/site-packages/docker/api/client.py", line 267, in _result
kernelci-pipeline-runner-docker |     self._raise_for_status(response)
kernelci-pipeline-runner-docker |   File "/usr/local/lib/python3.10/site-packages/docker/api/client.py", line 263, in _raise_for_status
kernelci-pipeline-runner-docker |     raise create_api_error_from_http_exception(e)
kernelci-pipeline-runner-docker |   File "/usr/local/lib/python3.10/site-packages/docker/errors.py", line 31, in create_api_error_from_http_exception
kernelci-pipeline-runner-docker |     raise cls(e, response=response, explanation=explanation)
kernelci-pipeline-runner-docker | docker.errors.APIError: 400 Client Error: Bad Request ("create data/ssh/: "data/ssh/" includes invalid characters for a local volume name, only "[a-zA-Z0-9][a-zA-Z0-9_.-]" are allowed. If you intended to pass a host directory, use absolute path")
kernelci-pipeline-runner-docker | 
kernelci-pipeline-runner-docker exited with code 1
```
Not sure if this is related to this PR.

**Comment by gctucker** [comment]
Was this in the `runner-docker` service?  I think it might be a Docker-in-Docker issue.  That shouldn't be related to this particular PR though, not sure what happened.  I can take a look later to try and reproduce it here.

**Comment by JenySadadia** [comment]
> Was this in the `runner-docker` service? 

Yes, it was in `runner-docker`.

> I can take a look later to try and reproduce it here.

OK. Thanks.

**Comment by gctucker** [comment]
I can't reproduce the Docker-in-Docker issue, it doesn't seem related to this PR and it worked on staging.  So I think we can merge this and open a GitHub issue to keep track of it as a follow-up.

**Pull request merged**
