### PR TITLE
docs: Add setup.md initial version

### PR DESCRIPTION
**Pull request by nuclearcat**
I am adding initial version to document important environment variables that are not documented anywhere.
This is initial version only, that will be extended in near future.

### CODE REVIEW

**Review by JenySadadia — COMMENTED** [review]
I think this should go to https://docs.kernelci.org/api_pipeline/api/local-instance/#setting-up-a-pipeline-instance.

**Comment by nuclearcat** [comment]
I think we will rather move part of that doc to pipeline, because documentation about each repository must belong to it.
If there is any documentation file that describe multiple repositories, it must be in kernelci-project.
It is counterintuitive to search documentation about how to set up pipeline instance - in api instance.
I suggest in that manual, we will put link to next chapter, so user click and go to pipeline instance setup, separate documentation.
We have to think how to rearrange everything.

**Comment by JenySadadia** [comment]
> I think we will rather move part of that doc to pipeline, because documentation about each repository must belong to it. If there is any documentation file that describe multiple repositories, it must be in kernelci-project. It is counterintuitive to search documentation about how to set up pipeline instance - in api instance. I suggest in that manual, we will put link to next chapter, so user click and go to pipeline instance setup, separate documentation. We have to think how to rearrange everything.

I think the idea was to centralize meastro's documentation and keep docs inside the repo as minimal as possible.
That's why we reduced content of `README.md` file for both the repo and moved everything possible to kernelci.org.
As we already have docs for setting up pipeline instance, it makes sense to me to move all the related docs to that location.

**Comment by nuclearcat** [comment]
Will be moved to API instance docs, but i believe it is wrong place to put docs how to setup pipeline instance.

**Pull request closed without merging**
