### PR TITLE
lava_callback.py: Sanitize lava log data

### PR DESCRIPTION
**Pull request by nuclearcat**
As we use this data in reports, lets remove all
non-printable characters as they confuse grafana, browsers and others.

### CODE REVIEW

**Comment by nuclearcat** [comment]
Unfortunately there is way more than just null characters.
For example take a look at: https://staging.kernelci.org:9000/viewer?node_id=6656ec0f8b971c830cc01c07
(This one not filtered yet)

**Comment by JenySadadia** [comment]
> Unfortunately there is way more than just null characters. For example take a look at: https://staging.kernelci.org:9000/viewer?node_id=6656ec0f8b971c830cc01c07 (This one not filtered yet)

Yes, but do you think replacing them with `?` would solve the issue?
Although this fix is not related to just KCIDB, from the KCIDB integration PoV, I'll be still getting validation error.

**Comment by nuclearcat** [comment]
I guess kcidb want to see only printable characters, isn't it?
What exactly is issue of kcidb validation is not that?

**Comment by JenySadadia** [comment]
> One issue is you are replacing new line char so it tries to accommodate everything in the log field now.

Check the log file https://staging.kernelci.org:9000/viewer?node_id=6657cdda2b005d102de7e3a1. Now, it just has one line with all the logs.

**Comment by nuclearcat** [comment]
I don't think i can truncate also length of lines, it might truncate some useful data, if some tests will generate very long lines for example.
Then we should do additional filtering in kcidb bridge according to grafana requirements.

**Comment by JenySadadia** [comment]
Can we just drop all the `\x00` chars from the log file if it won't cause any issues?

**Review by JenySadadia — APPROVED** [review]
Looks good on staging.
Verified log files.

**Comment by nuclearcat** [comment]
Thanks, merging

**Pull request merged**
