### PR TITLE
Submit data to KCIDB

### PR DESCRIPTION
**Pull request by JenySadadia**
Alternative to https://github.com/kernelci/kernelci-pipeline/pull/517
Related to https://github.com/kernelci/kcidb/issues/338
Depends on https://github.com/kernelci/kernelci-core/pull/2537, https://github.com/kernelci/kernelci-core/pull/2550

### CODE REVIEW

**Comment by JenySadadia** [comment]
Tested OK on staging:
https://kcidb.kernelci.org/d/revision/revision?orgId=1&var-datasource=playground&var-git_commit_hash=d2206c1a3338b71421ead1bc9d8f90f0f6f113c2&var-patchset_hash=&var-origin=kernelci_api&var-build_architecture=All&var-build_config_name=All&var-test_path=

**Comment by spbnick** [comment]
Thank you, Jeny! Looks pretty good! One thing that popped out at me, though, is the test paths are not complying with the schema:
image

Was this already fixed and these are simply old results?

Also, I wonder, could we perhaps assign the architecture kunit, and other similar tests were running on to the dummy build, instead of omitting it? And then add a note to the comment of the build, to help people distinguish and understand them?

**Comment by JenySadadia** [comment]
Thanks for verifying the submission.

All the nodes with `kbuild-` prefix are build nodes. That's why it doesn't have path set. Maybe you are referring to `subnodes` (such as nodes visible over [here](https://kcidb.kernelci.org/d/revision/revision?orgId=1&var-datasource=playground&var-git_commit_hash=9573979db04dfe52e7ca5e5eea73536924ae5f98&var-patchset_hash=&var-origin=kernelci_api&var-build_architecture=All&var-build_config_name=All&var-test_path=)).
I thought subnodes are root nodes/tets suite nodes for other tests.
Yes, I need to fix `kunit` path. Maybe `<dummy_build_node_name>.kunit` would work?

> Also, I wonder, could we perhaps assign the architecture kunit, and other similar tests were running on to the dummy build, instead of omitting it? And then add a note to the comment of the build, to help people distinguish and understand them?

Definitely.

**Comment by spbnick** [comment]
> All the nodes with kbuild- prefix are build nodes. That's why it doesn't have path set. Maybe you are referring to subnodes (such as nodes visible over [here](https://kcidb.kernelci.org/d/revision/revision?orgId=1&var-datasource=playground&var-git_commit_hash=9573979db04dfe52e7ca5e5eea73536924ae5f98&var-patchset_hash=&var-origin=kernelci_api&var-build_architecture=All&var-build_config_name=All&var-test_path=)).
I thought subnodes are root nodes/tets suite nodes for other tests.
Yes, I need to fix kunit path. Maybe <dummy_build_node_name>.kunit would work?

Umm, I'm not sure I understand this right. So e.g. this:

https://kcidb.kernelci.org/d/test/test?orgId=1&var-datasource=playground&var-origin=kernelci_api&var-build_architecture=All&var-build_config_name=All&var-id=kernelci_api:6621b8ce5f2e02af29641790

is a test? But it has a build in the path? If so, the test path is only used for categorizing the *test*, no build information should be there. We can get the build information by accessing its parent build (referenced via the `build_id` in the I/O data). Having build information in the test path prevents us from correlating it with tests from other submitters.

**Comment by JenySadadia** [comment]
> > All the nodes with kbuild- prefix are build nodes. That's why it doesn't have path set. Maybe you are referring to subnodes (such as nodes visible over [here](https://kcidb.kernelci.org/d/revision/revision?orgId=1&var-datasource=playground&var-git_commit_hash=9573979db04dfe52e7ca5e5eea73536924ae5f98&var-patchset_hash=&var-origin=kernelci_api&var-build_architecture=All&var-build_config_name=All&var-test_path=)).
> > I thought subnodes are root nodes/tets suite nodes for other tests.
> > Yes, I need to fix kunit path. Maybe <dummy_build_node_name>.kunit would work?
> 
> Umm, I'm not sure I understand this right. So e.g. this:
> 
> https://kcidb.kernelci.org/d/test/test?orgId=1&var-datasource=playground&var-origin=kernelci_api&var-build_architecture=All&var-build_config_name=All&var-id=kernelci_api:6621b8ce5f2e02af29641790
> 
> is a test? But it has a build in the path? If so, the test path is only used for categorizing the _test_, no build information should be there. We can get the build information by accessing its parent build (referenced via the `build_id` in the I/O data). Having build information in the test path prevents us from correlating it with tests from other submitters.

Okay. Got it. I'll send in a fix soon. Thanks.

**Comment by JenySadadia** [comment]
@spbnick Fixed the test node path.
Please verify if this looks OK:
https://kcidb.kernelci.org/d/checkout/checkout?orgId=1&var-datasource=playground&var-id=kernelci_api:66225446cdba2b039c9bacef&var-origin=All&var-build_architecture=All&var-build_config_name=All&var-test_path=

**Comment by spbnick** [comment]
Ah, this looks better, thank you. However, there are still architecture and other additional information in the paths, which I suspect shouldn't be there:

image

What do they (`-nfs-arm64-mediatek `, `-arm64-broonie `, etc.) exactly mean? They all start with `baseline`, are those actually the same test running in different environments with different parameters?

**Comment by JenySadadia** [comment]
> Ah, this looks better, thank you. However, there are still architecture and other additional information in the paths, which I suspect shouldn't be there:

Path names are based on test/job names in the API. See https://github.com/kernelci/kernelci-pipeline/blob/main/config/pipeline.yaml#L193. API will create a test node based on the job name. e.g. there will be a test node named `baseline-arm64` for job `baseline-arm64`. See for example https://staging.kernelci.org:9000/viewer?node_id=65b92ec111ee0a70c2f58a6b.

> What do they (`-nfs-arm64-mediatek `, `-arm64-broonie `, etc.) exactly mean? They all start with `baseline`, are those actually the same test running in different environments with different parameters?

Yes, these are different jobs that have different arch, config, compiler, runtime (e.g. lab), and other parameters.

**Comment by spbnick** [comment]
I see. However KCIDB requires the `path` to contain only test categorization, no other detail. The top level being the name of the test suite, and anything below being its subtests. The node names in KernelCI API are not mapping directly to that, and the extra details they contain are implementation-specific to KernelCI API. There are other places in KCIDB where that information should go. The architecture goes into builds, the lab name can go into `environment.misc` for now.

Having this information in the path is redundant and would prevent us from aggregating and comparing results with other CI systems, because they're built differently and don't have that information there.

There's a [test catalog](https://github.com/kernelci/kcidb/blob/main/tests.yaml), which describes what should go into the test path.

Essentially it's only `<test_suite>.<subtest>.<subtest>...`

E.g. take a look at how Microsoft does it: https://kcidb.kernelci.org/d/test-node/test-node?orgId=1&var-datasource=production&var-origin=microsoft&var-test_path=&var-build_architecture=All&var-build_config_name=All

This is the link to the top of the test tree they submit. If you look into "subnodes" panel, you'll see `ltp`, `kselftest`, and `microsoft_lisa` there - these are test suite names. If you click on any of them, you will see their subtests.

Here's an execution of `ltp.data_space`, which is to say the `data_space` subtest of the `ltp` test suite: https://kcidb.kernelci.org/d/test/test?orgId=1&var-datasource=production&var-id=microsoft:ltp-data_space-20240416143720937639&var-origin=microsoft&var-build_architecture=All&var-build_config_name=All

You can see the path of that test execution in the "Node" panel. The terminology is confusing yes. It's called "Node", because of how "test executions" claimed "test" name in the schema. It would be good to have this fixed, but it has nothing to do with KernelCI API's "Node".

Tell me if you'd like to have a call to go over this :heart:

**Comment by JenySadadia** [comment]
> I see. However KCIDB requires the `path` to contain only test categorization, no other detail. The top level being the name of the test suite, and anything below being its subtests. The node names in KernelCI API are not mapping directly to that, and the extra details they contain are implementation-specific to KernelCI API. There are other places in KCIDB where that information should go. The architecture goes into builds, the lab name can go into `environment.misc` for now.
> 
> Having this information in the path is redundant and would prevent us from aggregating and comparing results with other CI systems, because they're built differently and don't have that information there.
> 
> There's a [test catalog](https://github.com/kernelci/kcidb/blob/main/tests.yaml), which describes what should go into the test path.
> 
> Essentially it's only `<test_suite>.<subtest>.<subtest>...`
> 
> E.g. take a look at how Microsoft does it: https://kcidb.kernelci.org/d/test-node/test-node?orgId=1&var-datasource=production&var-origin=microsoft&var-test_path=&var-build_architecture=All&var-build_config_name=All
> 
> This is the link to the top of the test tree they submit. If you look into "subnodes" panel, you'll see `ltp`, `kselftest`, and `microsoft_lisa` there - these are test suite names. If you click on any of them, you will see their subtests.
> 
> Here's an execution of `ltp.data_space`, which is to say the `data_space` subtest of the `ltp` test suite: https://kcidb.kernelci.org/d/test/test?orgId=1&var-datasource=production&var-id=microsoft:ltp-data_space-20240416143720937639&var-origin=microsoft&var-build_architecture=All&var-build_config_name=All
> 
> You can see the path of that test execution in the "Node" panel. The terminology is confusing yes. It's called "Node", because of how "test executions" claimed "test" name in the schema. It would be good to have this fixed, but it has nothing to do with KernelCI API's "Node".
> 
> Tell me if you'd like to have a call to go over this ❤️

Thanks a lot for the insights and detailed explanation.

I have added a PR to add KernelCI test suits https://github.com/kernelci/kcidb/pull/520 and updated this one accordingly.
The test path should be fixed in the next staging run. I'll send in the results once it's verified on staging.

**Comment by JenySadadia** [comment]
Hello, @spbnick 
Does this look better https://kcidb.kernelci.org/d/revision/revision?orgId=1&var-datasource=playground&var-git_commit_hash=21fe9bbd57e5f3c2f0c48ed150ba511c0f9c8ee1&var-patchset_hash=&var-origin=kernelci_api&var-build_architecture=All&var-build_config_name=All&var-test_path=?

**Comment by JenySadadia** [comment]
OK. I have fixed the issue with `kunit` architecture. So the dummy build will now show arch info as well.
The dummy build node associated with `kver` test will have no arch info available as it runs natively (on shell) without architecture dependency.
Also, added extra data and output files for builds and tests.
Here is the latest submitted revision:
https://kcidb.kernelci.org/d/checkout/checkout?orgId=1&var-datasource=playground&var-id=kernelci_api:662cf34b5a8b8857c713862a&var-origin=All&var-build_architecture=All&var-build_config_name=All&var-test_path=
@spbnick I'd appreciate your feedback.

**Comment by spbnick** [comment]
Thank you, Jeny! It looks better now!

The top-level test nodes look good. I see, however, that you still have the old test node names under them. This is not really the province of KCIDB, and is up to the test suite author, but I don't think that's right. Do all these tests how subtests really? Some subnodes look again as the specification of the environment they ran in (which should be under "environment"), and that's not really a subtest. I.e. it's not a separate part of the code being executed. If they don't really have subtests, then e.g. just "kernelci_baseline" should  be sufficient. I see that kernelci_baseline also has baseline-nfs there. Is that a subtest, or just an execution of the same test with different parameters/environment? Same with kernelci_kver, which is probably so simple, that it can't have subtests, right? So it should also be just kernelci_kver?

OTOH, tast really seems to be a known test suite for ChromeOS, which KernelCI just happens to execute: https://chromium.googlesource.com/chromiumos/platform/tast/+/HEAD/README.md So it shouldn't be called `kernelci_tast`, but just `tast` instead. At the same time it seems to genuinely contain subtests, such as "decoder", "hardware", "kernel", "mm", and so on. And it also seems that "mm" has subtests too, such as "misc" and "decode". So these really should become tast.decoder, tast.hardware, tast.kernel, tast.mm.misc, tast.mm.decode, and so on. But, again, there should be no "-arm64-qualcomm" and such in those paths - the first is the architecture, which the test's build already specifies and an environment.

**Comment by JenySadadia** [comment]
Thanks for taking the time to review the results @spbnick :)

> Some subnodes look again as the specification of the environment they ran in (which should be under "environment"), and that's not really a subtest. I.e. it's not a separate part of the code being executed.

Yes, I understand but it's the KernelCI naming convention for different jobs. These are not sub-tests but different jobs with different runtime and platform. Yes, they do use the same test code template but with different parameters.
Please see `scheduler` section here: https://github.com/kernelci/kernelci-pipeline/blob/main/config/pipeline.yaml#L416.
For example, if you take a look at different `baseline` jobs, they have different configurations i.e. different `runtime`, `platform`, and `event` that will trigger this job:
```
- job: baseline-arm64
    event:
      channel: node
      name: kbuild-gcc-10-arm64
      result: pass
    runtime:
      type: lava
      name: lava-collabora
    platforms:
      - bcm2711-rpi-4-b
      - meson-g12b-a311d-khadas-vim3
      - rk3399-gru-kevin
      - rk3399-rock-pi-4b
      - rk3588-rock-5b
      - sun50i-h6-pine-h64

  - job: baseline-arm64-broonie
    event:
      channel: node
      name: kbuild-gcc-10-arm64
      result: pass
    runtime:
      type: lava
      name: lava-broonie
    platforms:
      - sun50i-h5-libretech-all-h3-cc
```

> Same with kernelci_kver, which is probably so simple, that it can't have subtests, right? So it should also be just kernelci_kver?

Yes, in this case, this is the only test. I can change it to have its name `kernelci_kver`.

> This is not really the province of KCIDB, and is up to the test suite author, but I don't think that's right.

I think every CI system would follow different naming conventions for the tests. If I may ask, how KCIDB would be affected by the test names?

> OTOH, tast really seems to be a known test suite for ChromeOS, which KernelCI just happens to execute: https://chromium.googlesource.com/chromiumos/platform/tast/+/HEAD/README.md So it shouldn't be called kernelci_tast, but just tast instead.

This should be fixed now.

> At the same time it seems to genuinely contain subtests, such as "decoder", "hardware", "kernel", "mm", and so on. And it also seems that "mm" has subtests too, such as "misc" and "decode". So these really should become tast.decoder, tast.hardware, tast.kernel, tast.mm.misc, tast.mm.decode, and so on. But, again, there should be no "-arm64-qualcomm" and such in those paths - the first is the architecture, which the test's build already specifies and an environment.

Again, this is how the tests have been named in KernelCI. See https://github.com/kernelci/kernelci-pipeline/blob/main/config/jobs-chromeos.yaml#L52.

**Comment by nuclearcat** [comment]
IMHO we can might add unified test name parameter in configuration file, if there is any test names "unification" and add it to the node or make mapping over configuration file, if it will help to keep somehow "standard" test names.

**Review by Anahyi — CHANGES_REQUESTED** [review]
src/send_kcidb.py

**Comment by JenySadadia** [comment]
Hello @spbnick  :)
Does this look better? https://kcidb.kernelci.org/d/revision/revision?orgId=1&var-datasource=playground&var-git_commit_hash=8f3a8b430c6394feb57eed76801d336d9c165013&var-patchset_hash=&var-origin=kernelci_api&var-build_architecture=All&var-build_config_name=All&var-test_path=
I am aware that `kselftest-cpufreq` test path still needs to be fixed as that test has just been added on staging. AFAICT other tests look good.

**Comment by JenySadadia** [comment]
Hello,
`kselftest-cpufreq` tests are also fixed now.
See the latest checkout: https://kcidb.kernelci.org/d/checkout/checkout?orgId=1&var-datasource=playground&var-id=kernelci_api:66332a7fb2978beeb2f90306&var-origin=All&var-build_architecture=All&var-build_config_name=All&var-test_path=

**Comment by spbnick** [comment]
Oh, this looks much better! Thank you, Jenny!

OK, here are some more comments:
* Why is there sometimes another `tast` test under `tast.<something>` tests? Like [this one](https://kcidb.kernelci.org/d/test/test?orgId=1&var-datasource=playground&var-origin=All&var-build_architecture=All&var-build_config_name=All&var-id=kernelci_api:66333054b2978beeb2f90b0b)?
* You seem to have both `baseline` and `baseline-nfs` **under** the `kernelci_baseline` test.
  * Is that intentional?
  * Do they have to repeat `baseline` in their name?
  * Are they different pieces of code?
* You seem to put the test output into the output files instead of the `log_url` field, and the link offers to download a compressed file. It would be nice to use the `log_url` field instead, and set the HTTP headers on the URLs so that the browser would simply open the (compressed) file itself. It speeds up triaging for humans. This is not urgent though, and can be done later.
* I'll have to crop those long configuration names in the build tables, as they make the lines taller, which turns on additional scrolling in the panels, making navigation more difficult. I have increased the size of the configuration panel on the build view, though.

**Comment by JenySadadia** [comment]
> * Why is there sometimes another `tast` test under `tast.<something>` tests? Like [this one](https://kcidb.kernelci.org/d/test/test?orgId=1&var-datasource=playground&var-origin=All&var-build_architecture=All&var-build_config_name=All&var-id=kernelci_api:66333054b2978beeb2f90b0b)?

That's a sub-test generated from lava job defintion. It stores result of lava test case named `0_tast`. See all the sub-test of its parent: https://staging.kernelci.org:9000/viewer?search=parent%3D66332e52b2978beeb2f905db

> * You seem to have both `baseline` and `baseline-nfs` **under** the `kernelci_baseline` test.
>   
>   * Is that intentional?
>   * Do they have to repeat `baseline` in their name?
>   * Are they different pieces of code?

`baseline` and `baseline-nfs` use the same test template but with different boot methods. The latter one uses `NFS` boot. Should I use only `kernelci_baseline` for both the tests instead?

> * You seem to put the test output into the output files instead of the `log_url` field, and the link offers to download a compressed file. It would be nice to use the `log_url` field instead, and set the HTTP headers on the URLs so that the browser would simply open the (compressed) file itself. It speeds up triaging for humans. This is not urgent though, and can be done later.

Yes, this needs to be fixed.

> * I'll have to crop those long configuration names in the build tables, as they make the lines taller, which turns on additional scrolling in the panels, making navigation more difficult. I have increased the size of the configuration panel on the build view, though.

Atm, I am assigning it the full configuration including `defconfig` and `fragment` options. I can assign only `defconfig` instead if we want to reduce the length.

**Comment by JenySadadia** [comment]
> Structure of our tests are like this, as i recall: mermaid-diagram-2024-05-02-152254
> 
> I think we need to report only leafs (green), as they are real tests, but not branches. But there is certain problems exist: Sometimes tast suite fail to execute. Then we should report tast (4th level, which usually branch, not leaf) failure. How?
> 
> Another problem, how we report tast tests names? audio.AloopLoadedFixture.stereo ? tast.audio.AloopLoadedFixture.stereo ? tast-sound-arm64-qualcomm.tast.audio.AloopLoadedFixture.stereo?

Thanks for the graph.
> Sometimes tast suite fail to execute. Then we should report tast (4th level, which usually branch, not leaf) failure. How?

@spbnick Do other CI systems submit test suite failures or just tests?
Let's say if `tast.basic.tast` suite failed. How do I report it?

Also, another point raised by @nuclearcat , if we have test `tast.basic.tast.login`, what should be path of it? I think we need to include the test suite in the path. But what would be the convention of KCIDB for it?

> Another problem, how we report tast tests names? audio.AloopLoadedFixture.stereo ? tast.audio.AloopLoadedFixture.stereo ? tast-sound-arm64-qualcomm.tast.audio.AloopLoadedFixture.stereo?

I have mapped test suite `tast-sound-arm64-qualcomm` to `tast.sound`. So I guess it would be `tast.sound.tast.audio.AloopLoadedFixture.stereo` as per the current mapping. But again it did include test suite name i.e. `tast`.

**Comment by JenySadadia** [comment]
Hi @spbnick 
I was looking into results submitted by other CI systems. I have a few questions to understand KCIDB schema.

- KernelCI old backend submitted this one https://kcidb.kernelci.org/d/test-node/test-node?orgId=1&var-datasource=production&var-origin=All&var-test_path=baseline&var-build_architecture=All&var-build_config_name=All.
It has `dmesg` and `login` as sub-nodes. So does it send just tests of those suites i.e. `crit`, `emerg` and so on?

- I am looking https://kcidb.kernelci.org/d/test-node/test-node?orgId=1&var-datasource=production&var-origin=All&var-test_path=kselftest.dt&var-build_architecture=All&var-build_config_name=All result from `broonie`'s lab.
So, does it send a seprate test node `kselftest.dt` or just a test path with other sub-tests?. Bdw its sub-tests have the test suite name in the `path` value e.g. https://kcidb.kernelci.org/d/test/test?orgId=1&var-datasource=production&var-id=broonie:0bab4cfd7c1560095e29919e2ebe01783b9096dc-sirena-203775&var-origin=All&var-build_architecture=All&var-build_config_name=All.
Correlated it with https://kcidb.kernelci.org/d/test-node/test-node?orgId=1&var-datasource=playground&var-origin=All&var-test_path=kselftest&var-build_architecture=All&var-build_config_name=All submitted by new API.

Please explain what does KCIDB expect as test data from a CI system. Does it only expect end tests results bypassing all the intermediate test suites/results?

**Comment by spbnick** [comment]
Sorry, Jeny, didn't see your comment before.

> KernelCI old backend submitted this one https://kcidb.kernelci.org/d/test-node/test-node?orgId=1&var-datasource=production&var-origin=All&var-test_path=baseline&var-build_architecture=All&var-build_config_name=All.
It has dmesg and login as sub-nodes. So does it send just tests of those suites i.e. crit, emerg and so on?

"Test nodes" are "virtual" objects and don't necessarily have corresponding "tests" in the database, but are extracted from them. That is, if you submit a "test" with a path `baseline.dmesg.alert`, you would be able to see *four* "nodes" in the dashboard:
* one for the root of the test tree, with empty "path",
* one for `baseline`,
* one for `baseline.dmesg`,
* and one for `baseline.dmesg.alert`.

Each of those nodes will have its status generated from tests at and below its path. So the "root node" would have the worst status of all tests, the `baseline` node would have the worst status of all tests with `baseline` path (if any) and all tests with a path starting with `baseline.`, the `baseline.dmesg` node would have the worst status of all tests with `baseline.dmesg` path (if any), and all tests with path starting with `baseline.dmesg.`, and so on.

So, it's sufficient to send **just** the tests corresponding to leaf nodes. You can also send tests for intermediate nodes, if you want. You can use that to e.g. lower the overall status of the test suite (e.g. specify `ERROR` if it aborted) and provide more information for the test suite as a whole. Depends on what you're trying to do.

> I am looking https://kcidb.kernelci.org/d/test-node/test-node?orgId=1&var-datasource=production&var-origin=All&var-test_path=kselftest.dt&var-build_architecture=All&var-build_config_name=All result from broonie's lab.
So, does it send a seprate test node kselftest.dt or just a test path with other sub-tests?

You can see all the actual tests at or below the node at the end of the page under "tests". There's a limit at how many tests are displayed there to reduce the load on the database and the browser, but I can't see intermediate nodes there. You can try sorting the panel by path and explore yourself. I'm not sure, however, what's exactly going on with those test names there, and if the path is formed completely correctly, as I don't run kselftest myself.

> Bdw its sub-tests have the test suite name in the path value e.g. https://kcidb.kernelci.org/d/test/test?orgId=1&var-datasource=production&var-id=broonie:0bab4cfd7c1560095e29919e2ebe01783b9096dc-sirena-203775&var-origin=All&var-build_architecture=All&var-build_config_name=All.

Do you mean that `kselftest.dt.dt_test_unprobed_devices_sh` contains `dt` twice? Yeah, that's suspicious, and could be wrong, but again I don't run kselftest myself. Perhaps the test suite calls them this way, and `dt` is repeated there as well, which would be unfortunate duplication, but correct from KCIDB standpoint, which is: test suites define names underneath the first item in the path.

> Correlated it with https://kcidb.kernelci.org/d/test-node/test-node?orgId=1&var-datasource=playground&var-origin=All&var-test_path=kselftest&var-build_architecture=All&var-build_config_name=All submitted by new API.

Now, I can see a few things wrong there, but please specify what exactly you're talking about.

> Please explain what does KCIDB expect as test data from a CI system. Does it only expect end tests results bypassing all the intermediate test suites/results?

I believe I answered this above, but just in case, it will handle test objects for leaf nodes only just fine, but you can also submit tests for intermediate nodes as well, keeping in mind the status calculation logic I outlined above.

**Comment by spbnick** [comment]
Aaaand, I missed another comment, sorry :grin: 

> I have mapped test suite `tast-sound-arm64-qualcomm` to `tast.sound`. So I guess it would be `tast.sound.tast.audio.AloopLoadedFixture.stereo` as per the current mapping. But again it did include test suite name i.e. `tast`. 

Um, sorry, why does it have to have `tast` twice? How does the execution of that `tast-sound-arm64-qualcomm` look like? Do you have a log? Are you asking it for a subset of tests somehow?

**Comment by spbnick** [comment]
> No, my question was, if the CI system sends `kselftest.dt` suite node to KCIDB or just test nodes directly i.e. `kselftest.dt.dt_test_unprobed_devices_sh` and so on?

Ah, yeah, as I said just the test nodes would be fine, but you can send intermediate nodes as well, if you need/want.

> If I choose to send test suite nodes along with leaf nodes, let's say KernelCI sends `baseline.dmesg` along with other test nodes i.e. `baseline.dmesg.crit`, how does KCIDB will evaluate test suite `baseline.dmesg` result? Would be calculated worst result or the one sent by the CI system?

The status of `baseline.dmesg` will be the worst one out of `baseline.dmesg` and `baseline.dmesg.crit`, with priority as described in https://kernelci.org/docs/kcidb/submitter_guide/#status

**Comment by JenySadadia** [comment]
I tried to fix the test path issue as per the current test suite naming scheme of KernelCI.
What do you think about this revision? @spbnick @nuclearcat 
https://kcidb.kernelci.org/d/checkout/checkout?orgId=1&var-datasource=playground&var-id=kernelci_api:663d11e44fdd42641c6498ac&var-origin=All&var-build_architecture=All&var-build_config_name=All&var-test_path=

**Comment by nuclearcat** [comment]
Naming of fluster tests and etc almost fine for me. Small details i noticed:
image
I noticed kernelmsg and login part of fluster.v4l2 tests, but i am not sure where they are belong.
I think @spbnick knows better where such tests belong:
@spbnick if you have test suite, for example that verify some subsystem, let's say kselftest.ping, but before reaching kselftest, there is integrity tests if system is booted, are they should be part of kselftest.ping or some kernelci_lava.login ?

**Comment by spbnick** [comment]
> I noticed kernelmsg and login part of fluster.v4l2 tests, but i am not sure where they are belong.
I think @spbnick knows better where such tests belong:
@spbnick if you have test suite, for example that verify some subsystem, let's say kselftest.ping, but before reaching kselftest, there is integrity tests if system is booted, are they should be part of kselftest.ping or some kernelci_lava.login ?

For simplicity, you can answer this question: "if you take the test suite and run it *outside* or *without* KernelCI, with the same parameters, would it have those tests there?" If your answer is "no", then they shouldn't be there.

Otherwise, these seem to be general checks before running the test suites. I don't know if you have an explicit test suite they belong to, but you can create a virtual one. Like `kernelci-basic`, or some such.

**Comment by spbnick** [comment]
Thank you, Jeny, this looks better and better. Aside from what @nuclearcat spotted, I'm also having my doubts about `tast` test naming. Looking through their code and documentation right now. Will update.

**Comment by spbnick** [comment]
OK, reading the [Tast: Writing Tests](https://chromium.googlesource.com/chromiumos/platform/tast/+/refs/heads/main/docs/writing_tests.md) guide, it seems that Tast tests are named following `<category>.<test>` pattern. So two levels only (three with the `tast` prefix). E.g. the original suite would have `typec.Basic` test, which we need to report as `tast.typec.Basic`.

In short, one can find all the categories in two files:
* https://chromium.googlesource.com/chromiumos/platform/tast-tests/+/refs/heads/main/src/go.chromium.org/tast-tests/cros/local/bundles/cros/imports.go
* https://chromium.googlesource.com/chromiumos/platform/tast-tests/+/refs/heads/main/src/go.chromium.org/tast-tests/cros/remote/bundles/cros/imports.go

The category name will be in the listed package names, as the last component, after `/cros/`. E.g. line `"go.chromium.org/tast-tests/cros/local/bundles/cros/camera"` points to the `camera` category, and the tests for the category are defined in that package.

Cross-checking your submission against that list of categories, I can see that there are three nodes that don't appear in the tast test suite, and must be KernelCI-specific:

* `kernelmsg`
* `os-release`
* `tast-tarball`

If they are *augmenting* the tast test suite, such as checking if the system produced any oops'es during the test execution, which `kernelmsg` could in theory be, then perhaps we can put them under `tast`, named something like `kernelci_kernelmsg`. The `os-release` and `tast-tarball` don't really seem applicable in that way, and likely shouldn't be there.

**Comment by JenySadadia** [comment]
> @JenySadadia, please go ahead and merge it when you're ready. It's totally fine to keep pushing data to playground. However, before we start pushing to production, we to get a new name for the KernelCI API/pipeline so that you can use it in the origins.

Yes, we'll change the origin name once a name is picked for the new system.

> Also, this doesn't seem right: image

Do you mean test names look weird or that they are failing?

**Comment by spbnick** [comment]
> Do you mean test names look weird or that they are failing?

The test names look totally weird. At the first level (and this is the first level) this should be a [well-known test suite name](https://github.com/kernelci/kcidb/blob/cf260b7696bdbc01f140ca913e71c798600edf6c/tests.yaml#L8-L15), and I can't imagine anyone just spell this out casually at a conference somewhere, let alone someone actually recognizing it (except by "that one test suite with crazy-long name", maybe) :joy:

**Comment by JenySadadia** [comment]
> > Do you mean test names look weird or that they are failing?
> 
> The test names look totally weird. At the first level (and this is the first level) this should be a [well-known test suite name](https://github.com/kernelci/kcidb/blob/cf260b7696bdbc01f140ca913e71c798600edf6c/tests.yaml#L8-L15)

Yes, that's because it's a new test being added. I added a comment https://github.com/kernelci/kernelci-pipeline/pull/622#discussion_r1628798802 to fix it.
 
> Also, this doesn't seem right: image

@nfraprado  Could you please take a look at test names? Why do the names look weird?

**Comment by spbnick** [comment]
> Yes, that's because it's a new test being added. I added a comment https://github.com/kernelci/kernelci-pipeline/pull/622#discussion_r1628798802 to fix it.

Perhaps the data for a test should come into KCIDB only if it is mapped?

@JenySadadia, @nuclearcat, what do you think?

**Comment by JenySadadia** [comment]
> > Yes, that's because it's a new test being added. I added a comment [#622 (comment)](https://github.com/kernelci/kernelci-pipeline/pull/622#discussion_r1628798802) to fix it.
> 
> Perhaps the data for a test should come into KCIDB only if it is mapped?
> 
> @JenySadadia, @nuclearcat, what do you think?

Yes, I agree. I need to add a few checks for it.

**Comment by JenySadadia** [comment]
As per the discussion on the community call, I'll merge this PR and create follow-up ones for further fixes.

**Comment by nfraprado** [comment]
@JenySadadia I added the KCIDB mapping to that test now. But am not sure if you were asking for something else too.

**Pull request merged**
