### PR TITLE
Convert email configs .env variables to TOML settings

### PR DESCRIPTION
**Pull request by JenySadadia**
To keep the settings in standard way, remove environment variables for email sender and recipient and convert them to command line arguments.

### CODE REVIEW

**Comment by JenySadadia** [comment]
`EMAIL_USER` can be removed as it should be the same as `email_sender`.

**Review by gctucker — APPROVED** [review]
LGTM - the whole thing for email reports will need to be rewritten anyway but yes the sending account settings will need to be stored in TOML so I think that's here to stay, more or less.

**Comment by JenySadadia** [comment]
Added `email_sender` and `email_recipient` to `staging.kernelci.org.secrets.toml`.

**Comment by gctucker** [comment]
The `email_recipient` recipient setting is typically the first thing that will be removed as it should end up in YAML instead for the system-wide settings.  We'll probably also have user-defined email preferences at some point in the future.

**Comment by gctucker** [comment]
Somehow the emails are still not getting through on https://groups.io/g/kernelci-results-staging/topics

There are no errors in the logs, the report content is being generated as expected.  So I'm not sure what's going on there.

**Comment by JenySadadia** [comment]
> Somehow the emails are still not getting through on https://groups.io/g/kernelci-results-staging/topics
> 
> There are no errors in the logs, the report content is being generated as expected. So I'm not sure what's going on there.

The staging config file `staging.kernelci.org.secrets.toml` is already been updated with the email sender and recipient settings.
That should have worked.

**Comment by gctucker** [comment]
> That should have worked.

Except it doesn't :sweat_smile:

**Pull request merged**
