### PR TITLE
src/timeout.py: fix some pylint errors

### PR DESCRIPTION
**Pull request by gctucker**
Fix some pylint errors in timeout.py to drop unused imports and avoid reusing variable names in nested scopes.

### CODE REVIEW

**Review by JenySadadia — CHANGES_REQUESTED** [review]
`pylint` will also complain about missing module and class docstring.

**Comment by gctucker** [comment]
> `pylint` will also complain about missing module and class docstring.

I know. This is only fixing some of the errors.

**Comment by JenySadadia** [comment]
> > `pylint` will also complain about missing module and class docstring.
> 
> I know. This is only fixing some of the errors.

OK. I think we should enable `pylint` for all the services.

**Review by JenySadadia — APPROVED** [review]

**Comment by gctucker** [comment]
No I don't think we should enable pylint as part of the GitHub actions as the code is being rewritten all the time.  I just wanted to fix these errors to avoid subtle bugs.

**Comment by gctucker** [comment]
@JenySadadia Are you waiting for something else before merging this PR?

**Comment by JenySadadia** [comment]
> @JenySadadia Are you waiting for something else before merging this PR?

Nope, I think it is ready to merge.

**Pull request merged**
