### PR TITLE
src/send_kcidb: submit all job nodes

### PR DESCRIPTION
**Pull request by JenySadadia**
For the convenience of data analysis on KCIDB dashboard, submit all the job nodes irrespective of node results.

### CODE REVIEW

**Review by laura-nao — APPROVED** [review]
LGTM, thanks a lot @JenySadadia !

**Comment by JenySadadia** [comment]
This PR isn't verified yet.

**Comment by JenySadadia** [comment]
OK, it worked for `dtbs_check` job: https://kcidb.kernelci.org/d/test-node/test-node?orgId=1&var-datasource=playground&var-origin=maestro&var-test_path=dtbs_check&var-build_architecture=All&var-build_config_name=All
But not able to see any passed boot test though.
Could you please verify? @laura-nao

**Comment by laura-nao** [comment]
@JenySadadia I can see `boot` and `boot.nfs` passed tests on recent runs - e.g.:
- [boot](https://fresh-kcidb-grafana-m6io3uhhiq-uc.a.run.app/d/test/test?orgId=1&var-datasource=cdmoe4lcafu2od&var-origin=maestro&var-build_architecture=arm64&var-build_config_name=defconfig&var-id=maestro:66a9bf896ea2cf32b6886c7e)
- [boot.nfs](https://fresh-kcidb-grafana-m6io3uhhiq-uc.a.run.app/d/test/test?orgId=1&var-datasource=cdmoe4lcafu2od&var-origin=maestro&var-build_architecture=arm64&var-build_config_name=cros://chromeos-6.6/arm64/chromiumos-mediatek.flavour.config&var-id=maestro:66a9bddd6ea2cf32b6885273)

So seems like it worked. Thanks!

**Pull request merged**
