### PR TITLE
config: pipeline: enable android baseline (boot) testing for arm and arm64 in only allmodconfig

### PR DESCRIPTION
**Pull request by musamaanjum**

### CODE REVIEW

**Comment by JenySadadia** [comment]
This PR is breaking staging. Newly added jobs are missing `template` field in the definition.

**Comment by musamaanjum** [comment]
> This PR is breaking staging. Newly added jobs are missing `template` field in the definition.

@JenySadadia doesn't the `baseline.jinja2` be used for these new android baseline tests? Can you point to exactly where the template is missing?

```
  baseline-arm64-qualcomm: *baseline-job
  baseline-arm64-android: *baseline-job
```

**Comment by JenySadadia** [comment]
> > This PR is breaking staging. Newly added jobs are missing `template` field in the definition.
> 
> @JenySadadia doesn't the `baseline.jinja2` be used for these new android baseline tests? Can you point to exactly where the template is missing?
> 
> ```
>   baseline-arm64-qualcomm: *baseline-job
>   baseline-arm64-android: *baseline-job
> ```

You're right. Sorry, my bad! The staging was breaking due to https://github.com/kernelci/kernelci-pipeline/pull/648/files instead.

**Comment by musamaanjum** [comment]
@nuclearcat PR seems good. But I've not found results with the result-summary. Please can you try verifying the results on your end?

**Comment by musamaanjum** [comment]
> @nuclearcat PR seems good. But I've not found results with the result-summary. Please can you try verifying the results on your end?

Verfieid the results: 
[baseline.html.txt](https://github.com/user-attachments/files/16123117/baseline.html.txt)

PR is ready for merging now.

**Comment by nuclearcat** [comment]
Thank you Usama, for contribution and verifying results! Merging now

**Comment by pawiecz** [comment]
This PR changed `platforms` section in the unrelated schedule disabling TestJob submission to `lava-qualcomm` lab (fix is on the way)

**Pull request merged**
