### PR TITLE
T38685 src/test_report: prevent empty test report generation

### PR DESCRIPTION
**Pull request by JenySadadia**
Fixes https://github.com/kernelci/kernelci-pipeline/issues/168

Signed-off-by: Jeny Sadadia <jeny.sadadia@collabora.com>

### CODE REVIEW

**Comment by JenySadadia** [comment]
Tested OK on staging:

Notifier logs:
```
today at 13:33:3711/09/2022 08:03:37 AM UTC [INFO] Listening for events... 
today at 13:33:3711/09/2022 08:03:37 AM UTC [INFO] Press Ctrl-C to stop.
today at 13:33:3711/09/2022 08:03:37 AM UTC [INFO] Time                        Commit        Node Id                   State      Result    Name
today at 13:33:3811/09/2022 08:03:38 AM UTC [INFO] 2022-11-09 08:03:38.348539  b18c56f63185  636b5eda8f94e20c6826ba98  Running    -         checkout
today at 13:36:0311/09/2022 08:06:03 AM UTC [INFO] 2022-11-09 08:06:02.970120  5b82e1ebf42f  636a0dba8f94e20c6826ba93  Done       Incomplete  checkout
```

Test report logs:
```
today at 13:33:3711/09/2022 08:03:37 AM UTC [INFO] Listening for completed nodes
today at 13:33:3711/09/2022 08:03:37 AM UTC [INFO] Press Ctrl-C to stop.
```

**Comment by gctucker** [comment]
What happens when an email report is sent with an incomplete root node?  We need to send reports about failures too, I wonder if it's generating anything useful at the moment.

**Comment by JenySadadia** [comment]
> What happens when an email report is sent with an incomplete root node? We need to send reports about failures too, I wonder if it's generating anything useful at the moment.

`checkout` will not have any child node if it is incomplete. So, the report will just have `checkout` node info. Please take a look at the test report here: https://github.com/kernelci/kernelci-pipeline/issues/168#issue-1432722756

**Comment by JenySadadia** [comment]
Updated test report for checkout failures:


```
kernelci-pipeline-test_report | kernelci/staging-stable None: Failed to create source tarball for checkout
kernelci-pipeline-test_report | 
kernelci-pipeline-test_report | Summary
kernelci-pipeline-test_report | =======
kernelci-pipeline-test_report | 
kernelci-pipeline-test_report | Tree:     kernelci
kernelci-pipeline-test_report | Branch:   staging-stable
kernelci-pipeline-test_report | Describe: None
kernelci-pipeline-test_report | URL:      https://github.com/kernelci/linux.git
kernelci-pipeline-test_report | SHA1:     29191dc12380b9fd00600a8b9a63d96baaec473d

```

**Review by gctucker — APPROVED** [review]

**Pull request merged**
