### PR TITLE
pipeline.yaml: Add Chromebook for testing on x86-board kernels

### PR DESCRIPTION
**Pull request by nuclearcat**
Add first Chromebook in pipeline testing

Depends-on: https://github.com/kernelci/kernelci-core/pull/2176

### CODE REVIEW

**Comment by pawiecz** [comment]
I should be able to verify this change (to certain extent) in my dev setup - let me check this patch and report back.

**Comment by nuclearcat** [comment]
> I should be able to verify this change (to certain extent) in my dev setup - let me check this patch and report back.

It depends also on https://github.com/kernelci/kernelci-core/pull/2176 , i will add it on PR

**Comment by gctucker** [comment]
It would be really good to complete the job configuration work first, so we don't have to fill the YAML file with all the possible combinations we'll want to run.  So while it's probably a good idea to add a couple of platforms like this, before adding any more the features should be implemented for this to scale with wildcards or regexes or something other than everything hard-coded.

**Comment by pawiecz** [comment]
Unfortunately verification of this patch allowed me only to confirm the behavior observed on the staging instance.

Here's what I've done:
- shorten pipeline to depend on `kver` instead if `kbuild-*` job (no K8s in the local setup)
- run pipeline with `kernelci/staging-kernelci` images (requires LAVA submission credentials)
- run pipeline with custom container images [0] with mocked LAVA TestJob submission

This results in running `baseline-x86` job, but not the `-board` one. I'll dig into triggering mechanisms unless that's something @nuclearcat's working already (I don't want to duplicate work).

We can also split the investigation, e.g. I'll have a look bottom-up (scheduler-lava -> scheduler -> pipeline) while you check top-down (pipeline -> checkout -> kbuild -> trigger) if that makes sense - let me know what would work best for you.

[0] uploaded to: https://github.com/pawiecz/kernelci-core/tree/add-depthcharge
edited: `config/docker/fragment/kernelci.jinja2` and later pipeline's `docker-compose.yaml`
rebuilt with: `./kci docker build kernelci --prefix=boards/ --no-cache`

**Comment by pawiecz** [comment]
Verified together with kernelci/kernelci-core#2176 (and a minor fixup PR) on a local instance:

1. LAVA job definition was properly rendered
2. Scheduler-LAVA job was triggered and mock TestJob sumission was run
3. LAVA TestJob completed successfully: https://lava.collabora.dev/scheduler/job/12007421

LGTM (after fixup is pulled and squashed to the patch)

**Pull request merged**
