### PR TITLE
src: update all services to use new API.User class

### PR DESCRIPTION
**Pull request by gctucker**
Use the new API.User bindings class in all services for user-related operations.

### CODE REVIEW

**Comment by gctucker** [comment]
This is not related to this PR, it's about node states whereas this PR is about users.

Then the issue is that #372 is not being deployed on staging due to a conflict with an earlier PR:

```
PR   User             Branch                           Status
-------------------------------------------------------------
 297 yurinnick        test-report-patchwork            SKIP label: staging-skip
 299 yurinnick        kcidb-patchset                   SKIP label: staging-skip
 342 yurinnick        patchset-service                 SKIP label: staging-skip
 363 hardboprobot     fix-monitor-nodes-only           OK
 364 nuclearcat       add-trigger-ownership            OK
 365 hardboprobot     rework-models                    SKIP label: staging-skip
 367 nuclearcat       workaround-exception-submit      OK
 369 nuclearcat       fix-default-value                OK
 370 a-wai            more-chromebooks                 OK
 371 nuclearcat       use-kbuild-for-kbuild            OK
 372 gctucker         update-api-bindings              FAILED to pull
 373 gctucker         user-api-bindings                OK
```

**Comment by gctucker** [comment]
@nuclearcat Updated with the missing bit in `timeout.py`.

**Comment by nuclearcat** [comment]
```
  today at 6:28:43 PMTraceback (most recent call last):
    today at 6:28:43 PM  File "/home/kernelci/./pipeline/trigger.py", line 160, in <module>
    today at 6:28:43 PM    status = opts.command(configs, opts)
    today at 6:28:43 PM             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
    today at 6:28:43 PM  File "/home/kernelci/./pipeline/trigger.py", line 153, in __call__
    today at 6:28:43 PM    return Trigger(configs, args).run(args)
    today at 6:28:43 PM           ^^^^^^^^^^^^^^^^^^^^^^
    today at 6:28:43 PM  File "/home/kernelci/./pipeline/trigger.py", line 31, in __init__
    today at 6:28:43 PM    self._current_user = self._api.whoami()
    today at 6:28:43 PM                         ^^^^^^^^^^^^^^^^
    today at 6:28:43 PMAttributeError: 'LatestAPI' object has no attribute 'whoami'
    today at 6:30:50 PMContainer stopped
    ```
    There is still issue, some of calls need to be changed to user.whoami

**Comment by gctucker** [comment]
Sorry, forgot to `git add` amidst all the noise.  I'm done for today now.

**Comment by nuclearcat** [comment]
Is it ready for merge? As it is tested on staging and necessary to not have main branch broken.

**Comment by gctucker** [comment]
I made it a draft PR as the `kernelci-core` changes needed to be merged first.  I'll update it now as it should be ready, yes.

**Review by JenySadadia — APPROVED** [review]

**Pull request merged**
