### PR TITLE
config/kernelci.conf: add staging db config

### PR DESCRIPTION
**Pull request by gctucker**
Add entry in kernelci.conf for the staging.kernelci.org db config.
This can be used by anyone with an API token.

Signed-off-by: Guillaume Tucker <guillaume.tucker@collabora.com>

### CODE REVIEW

**Review by JenySadadia — COMMENTED** [review]
LGTM.

I tested it on local, I removed `db:docker-host` entry and added `db:staging.kernelci.org` to kernelci.conf.
I am still getting `docker-host` as `args.db_config` when I run client containers.
Why is that so?

**Comment by gctucker** [comment]
> LGTM.
> 
> I tested it on local, I removed `db:docker-host` entry and added `db:staging.kernelci.org` to kernelci.conf. I am still getting `docker-host` as `args.db_config` when I run client containers. Why is that so?

Because of this at the top of the file:
```ini
[DEFAULT]
db_config: docker-host
```

**Comment by JenySadadia** [comment]
> > LGTM.
> > I tested it on local, I removed `db:docker-host` entry and added `db:staging.kernelci.org` to kernelci.conf. I am still getting `docker-host` as `args.db_config` when I run client containers. Why is that so?
> 
> Because of this at the top of the file:
> 
> ```ini
> [DEFAULT]
> db_config: docker-host
> ```

Oh, okay.
It works now. Thanks.

**Comment by gctucker** [comment]
BTW You can override that with the `--db-config` option if you run the container by hand.  For example:

```
$ docker-compose run runner /bin/bash
kernelci@804e7cceffbf:~$ ./pipeline/runner.py run --db-config=staging.kernelci.org
```

**Pull request merged**
