### PR TITLE
Add CIP tree with default builds

### PR DESCRIPTION
**Pull request by patersonc**
Add CIP tree and the relevant branches as requested in https://github.com/kernelci/kernelci-core/issues/2711.

Currently this PR only adds basic build support.
We'll also need to tailor what is build, and what is tested...

Whilst at it, add in a couple of minor code fixups.

### CODE REVIEW

**Comment by patersonc** [comment]
Cc @helen-fornazier

**Comment by patersonc** [comment]
One thing to consider before merging this, is whether the kernelCI project wants to split off CIP configuration off into a separate file as was done in the legacy system. It looks like something similar has been done for chromeos.

**Comment by pawiecz** [comment]
@patersonc Config split (for sections: platforms/jobs/schedules) is on the roadmap. CIP-related bits could also be put in a separate set of pipeline config files. This patch set is fine to be merged as it is.

**Review by pawiecz — APPROVED** [review]
LGTM

**Comment by nuclearcat** [comment]
Tested with: kci-dev.py checkout --giturl https://git.kernel.org/pub/scm/linux/kernel/git/cip/linux-cip.git --branch linux-6.1.y-cip-rt --tipoftree

https://staging.kernelci.org:9000/viewer?search=parent%3D6710274fab53a65f0e2e4e3b

**Pull request merged**
