### PR TITLE
fix(docker/k8s): Fix image names

### PR DESCRIPTION
**Pull request by nuclearcat**
This commit depends on PR https://github.com/kernelci/kernelci-core/pull/2705

### CODE REVIEW

**Review by pawiecz — DISMISSED** [review]
If there's a need to be more flexible with image registries, there are two more ways to handle it:

1. make requested registry a Job param (also setting e.g. `ghcr.io` as a default)
2. explicitly include registry in the image identifier

Hiding this information to create a [magic](https://en.wikipedia.org/wiki/Magic_number_(programming)) character `/` could become confusing to the config that's not an easy one to grasp in the first place.

**Comment by pawiecz** [comment]
As I went through the PR this one depends on I see that there's even more implicit changes: non-prod instances will receive different set of images (unless there's a magic character in their configured name).

Do these changes address previous "hack with hardcoding"? Sure! But they also introduce a set of new ones buried deeper in the pipeline service logic instead of its configuration/job template.

**Comment by nuclearcat** [comment]
We cannot set it in pipeline configuration, as it is shared by both prod and staging instance, so it means it should be in "instance-specific" configuration file - toml file.
My suggestion is to move these hardcoded values to toml configuration file (whoever can implement it).
/ is not magic character, it is indication that registry or username is set, and if it is set - we dont use default value of ghcr.io.

**Comment by pawiecz** [comment]
> We cannot set it in pipeline configuration, as it is shared by both prod and staging instance, so it means it should be in "instance-specific" configuration file - toml file.

Sure we can - pipeline configuration should include pipeline-instance-specific values.

I agree that maintaining two files and keeping them in sync might become error prone. This case could be covered by keeping a prod config in repo and patch it with sed for staging environment. This way instance configuration stays in a static file, not service logic.

> My suggestion is to move these hardcoded values to toml configuration file (whoever can implement it).

This brings another layer of config. In this case more is not merrier. I realize toml is already utilized for secrets (which obviously cannot be kept publicly) but adding more options there makes config even more confusing - like configuring Maestro Tasks through two or more layers of templates in two different repositories (pipline:config/runtime and core:config/runtime)

> / is not magic character, it is indication that registry or username is set, and if it is set - we dont use default value of ghcr.io.

True, it's not magic by itself, core#2705 makes it so. You can have images built locally containing slashes which are not bound to specific user/group/registry but you won't be able to use them because service logic will process those as if they were an external resource.

KCI image build process with tags indicating available features has been confusing enough.

I don't have the capacity to prevent all the changes that I disagree with from being introduced in the repo, especially when they address crucial issues like pulling wrong container images (here). 

Let the tech debt grow - together with debugging/maintenance "interest rate"

**Comment by nuclearcat** [comment]
> I don't have the capacity to prevent all the changes that I disagree with from being introduced in the repo, especially when they address crucial issues like pulling wrong container images (here).
Actually this is why feedback is here.

If you suggest magic is no-no, i think better i remove it, and leave just basic image name. And i believe you are right on this point.
Because this behavior need to be documented, and it is not easy to do, so better to keep things simple as possible. I will update PR.
toml is used not only as secrets, but i believe it will be "instance specific" configuration file. Probably everything instance specific will move there.

**Pull request merged**
