### PR TITLE
Handle incomplete/failed checkout

### PR DESCRIPTION
**Pull request by JenySadadia**
Fixes https://github.com/kernelci/kernelci-pipeline/issues/554
Depends on https://github.com/kernelci/kernelci-core/pull/2507

- Tarball updates source code repo and creates tarball. If update repo operation fails even with the second attempt, it means it failed to checkout souce code. Hence, update `checkout` node with state `done` state and result `fail`.
- Set timed-out `checkout` node result to `incomplete` while in `running` state. As it denotes that the node timed-out while checkout was still going on.

### CODE REVIEW

**Review by nuclearcat — CHANGES_REQUESTED** [review]
Maybe we can add error_code as well (probably need to introduce new one) to indicate reason why node is incomplete. It will help to troubleshoot incomplete issues.

**Comment by JenySadadia** [comment]
> Maybe we can add error_code as well (probably need to introduce new one) to indicate reason why node is incomplete. It will help to troubleshoot incomplete issues.

Yes, definitely. I'll update the PR.

**Comment by JenySadadia** [comment]
Timeout worked. Error info is not set as the updated PR just got deployed on staging.
https://staging.kernelci.org:9000/viewer?node_id=6621c39d5f2e02af29643459

**Comment by nuclearcat** [comment]
I think its fine to merge, as its not crashing on staging, and if any corner case will appear, we will follow up

**Pull request merged**
