### PR TITLE
Fix `checkout` node transition to `done` state

### PR DESCRIPTION
**Pull request by JenySadadia**
Fixes https://github.com/kernelci/kernelci-pipeline/issues/548
Created on top of https://github.com/kernelci/kernelci-pipeline/pull/556 to avoid merge conflicts.

### CODE REVIEW

**Comment by JenySadadia** [comment]
`timeout-closing` is working as expected:
```
25/04/2024 20:18:15 04/25/2024 02:48:15 PM UTC [DEBUG] 662a44e1671150e1eda8ba92 RUNNING: 0
25/04/2024 20:18:16 04/25/2024 02:48:16 PM UTC [DEBUG] 662a44e1671150e1eda8ba92 RUNNING build child nodes: 33
```

**Comment by JenySadadia** [comment]
I still need to verify `timeout` mode.

**Comment by JenySadadia** [comment]
Tested OK locally.

**Review by nuclearcat — APPROVED** [review]
LGTM

**Pull request merged**
