### PR TITLE
Use timed rotation logging

### PR DESCRIPTION
**Pull request by JenySadadia**
Fixes https://github.com/kernelci/kernelci-pipeline/issues/682

Use timed rotating file handler to optimize storage space for log files instead of using a regular file handler.
It will create a new log file with `<service-name>.log` convention and keep one backup file for older logs than
7 days. It will delete older backup log files on rollover if exists.
In case of `logs` directory is not mounted due to a different environment such as `k8s`, the service would crash with
`FileNotFoundError`. Enable only console logging when file logging fails to fix the issue.

### CODE REVIEW

**Review by nuclearcat — APPROVED** [review]
Amazing, exactly what we need. Thank you Jeny, again, for saving the day. I might roll tomorrow (Friday) production, but... might be bad idea, i will explain why, it might wait until Monday.

**Comment by JenySadadia** [comment]
Thank you Denys :)
Atm I have set the rotation duration to 7 days. I guess we should set at least 15 days.
What should we keep from storage PoV?

**Comment by nuclearcat** [comment]
I think this logs wont take much space, so 15 days should be fine.

**Comment by JenySadadia** [comment]
> I think this logs wont take much space, so 15 days should be fine.

Thanks. Updated the config to keep 15 days.

**Comment by nuclearcat** [comment]
Seems working on staging fine, will test on k8s deploy today. Merging.

**Pull request merged**
