### PR TITLE
T42283 Convert user settings to TOML format

### PR DESCRIPTION
**Pull request by JenySadadia**
Depends on https://github.com/kernelci/kernelci-core/pull/1936

Convert user settings from `.conf` to `.toml`:
- Add `kernelci.toml` file
- Update docker services to use the latest settings file

### CODE REVIEW

**Comment by JenySadadia** [comment]
We can remove `kernelci.conf` once it becomes functional.

**Comment by JenySadadia** [comment]
> It would be good to try this with the `staging.kernelci.org.conf` file used on staging with the new pipeline, see the patch in `kernelci-deploy` which adds the file.

Actually, I am struggling to make this work even locally.
Somehow it is not able to map configuration with yaml file.
```
kernelci-pipeline-trigger | Traceback (most recent call last):
kernelci-pipeline-trigger |   File "/home/kernelci/./pipeline/trigger.py", line 148, in <module>
kernelci-pipeline-trigger |     status = opts.command(configs, opts)
kernelci-pipeline-trigger |   File "/home/kernelci/./pipeline/trigger.py", line 142, in __call__
kernelci-pipeline-trigger |     return Trigger(configs, args).run(args)
kernelci-pipeline-trigger |   File "/home/kernelci/./pipeline/trigger.py", line 29, in __init__
kernelci-pipeline-trigger |     super().__init__(configs, args, 'trigger')
kernelci-pipeline-trigger |   File "/home/kernelci/pipeline/base.py", line 27, in __init__
kernelci-pipeline-trigger |     self._api_config = configs['api_configs'][args.api_config]
kernelci-pipeline-trigger | KeyError: '"docker-host"'
```

**Comment by JenySadadia** [comment]
> > It would be good to try this with the `staging.kernelci.org.conf` file used on staging with the new pipeline, see the patch in `kernelci-deploy` which adds the file.
> 
> Actually, I am struggling to make this work even locally. Somehow it is not able to map configuration with yaml file.
> 
> ```
> kernelci-pipeline-trigger | Traceback (most recent call last):
> kernelci-pipeline-trigger |   File "/home/kernelci/./pipeline/trigger.py", line 148, in <module>
> kernelci-pipeline-trigger |     status = opts.command(configs, opts)
> kernelci-pipeline-trigger |   File "/home/kernelci/./pipeline/trigger.py", line 142, in __call__
> kernelci-pipeline-trigger |     return Trigger(configs, args).run(args)
> kernelci-pipeline-trigger |   File "/home/kernelci/./pipeline/trigger.py", line 29, in __init__
> kernelci-pipeline-trigger |     super().__init__(configs, args, 'trigger')
> kernelci-pipeline-trigger |   File "/home/kernelci/pipeline/base.py", line 27, in __init__
> kernelci-pipeline-trigger |     self._api_config = configs['api_configs'][args.api_config]
> kernelci-pipeline-trigger | KeyError: '"docker-host"'
> ```

Oh, it is working now.
The issue was it was using an older `kernelci/staging-kernelci` image.

**Comment by JenySadadia** [comment]
Tested OK on staging.

Attaching test report:
```
today at 17:16:00[STAGING] kernelci/staging-mainline staging-mainline-20230525.5: 4 runs 0 failures
today at 17:16:00
today at 17:16:00Summary
today at 17:16:00=======
today at 17:16:00
today at 17:16:00Tree:     kernelci
today at 17:16:00Branch:   staging-mainline
today at 17:16:00Describe: staging-mainline-20230525.5
today at 17:16:00URL:      https://github.com/kernelci/linux.git
today at 17:16:00SHA1:     3085dba4e3f5fa9c4d868a76d7e103f8137cb51f
today at 17:16:00Name            | Result   | Total    | Failures
today at 17:16:00----------------+----------+----------+---------
today at 17:16:00kunit           | pass     |        3 |        0
today at 17:16:00kbuild-gcc-10-x86 | pass     |        5 |        0
today at 17:16:00kver            | pass     |        0 |        0
today at 17:16:00kunit-x86_64    | pass     |      361 |        1
today at 17:16:00
today at 17:16:00
today at 17:16:00Failing tests
today at 17:16:00=============
today at 17:16:00
today at 17:16:00kunit-x86_64
today at 17:16:00------------
today at 17:16:00
today at 17:16:00* exec.input_core.input_test_match_device_id
```

**Comment by gctucker** [comment]
OK this has been tested on staging so I think we can merge it now.  If we decide to move to using dotted keys in TOML later on then we can always rework the settings file accordingly etc.  Doing this shouldn't cause any code changes in the pipeline services anyway, just the TOML table names.

**Pull request merged**
